apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  tags:
    - test
  annotations:
    github.com/project-slug: h4yde/test
spec:
  type: service
  lifecycle: unknown
  owner: Wizeline Backstage Team
  system: test
